version: '3.8'
services:
   app:
      container_name: app-spring-rent
      image: app-spring-rent
      build: ./
      ports:
         - "8080:8080"
      depends_on:
         - rent-db
   db:
      container_name: rent-db
      image: postgres
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=mydbb